---
- name: Provision DB
  hosts: all
  become: true
  tasks:

    - name: Install services package
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
        update_cache: yes
        state: present

    - name: Add signing key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-4.2.asc
        state: present

    - name: Add repository MongoDB
      apt_repository:
        repo: deb https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse
        state: present
        update_cache: yes
        filename: mongodb-org-4.2

    - name : Install MongoDB
      apt:
        name: mongodb-org
        install_recommends: yes
        state: present
        update_cache: yes

    - name: Enable and start service MongoDB
      systemd:
        name: mongod
        state: started
        enabled: yes
